apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: webapp-sql
    tier: backend
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb
  labels:
    app: webapp-sql
    tier: backend
spec:
  selector:
    matchLabels:
      app: webapp-sql
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-sql
        tier: backend
    spec:
      containers:
      -image: mysql:5.7
       name: mysql
       env:
       - name: MYSQL_ROOT_PASSWORD
         value: rootpassword
       - name: MYSQL_USER
         value: bharath
       - name: MYSQL_PASSWORD
         value: bharathpass 
       - name: MYSQL_DATABASE
         value: tutorial
       args: ["--default-authentication-pulgin=mysql_native_password"] 
       ports:
       - containerPort: 3306
       volumeMounts:
       - name: mysql-persistent-storage
         mountPath: /var/lib/mysql
     volumes:
     - name: mysql-persistent-storage
       peristantVolumeClaim:
         claimName: mysql-pv-claim
        
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
