apiVersion: v1
kind: Service
metadata:
  name: php-deployment
spec:
  selector:
    app: webapp-sql
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-sql
  labels:
    app: webapp-sql
    tier: frontend
spec:
  selector:
    matchLabels:
      app: webapp-sql
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-sql
        tier: frontend
    spec:
      containers:
      - name: webapp1
        image: bharathreddyboppidi/bharath-php-mysql:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
    
    
        
